create table if not exists public.students(id bigint generated by default as identity primary key,name text not null,email text unique not null,created_at timestamptz default now());
alter table public.students enable row level security;
create policy "Students are readable" on public.students for select to authenticated using (true);
create policy "Users can insert students" on public.students for insert to authenticated with check (true);
create table if not exists public.audit_log(id bigint generated by default as identity primary key,action text not null,created_at timestamptz default now());
create or replace function public.log_student_insert() returns trigger language plpgsql as $$ begin insert into public.audit_log(action) values ('student inserted'); return new; end; $$;
create trigger student_insert_audit after insert on public.students for each row execute function public.log_student_insert();
